import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

describe("security.txt (RFC 9116)", () => {
  const txt = readFileSync("public/.well-known/security.txt", "utf8");

  it("has the required Contact and Expires fields", () => {
    expect(txt).toMatch(/^Contact: mailto:.+@.+$/m);
    expect(txt).toMatch(/^Expires: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/m);
  });

  it("has not expired", () => {
    // An expired security.txt is worse than none — it signals the policy is
    // abandoned. Regenerated by the prebuild step on every deploy.
    const expires = /^Expires: (.+)$/m.exec(txt)?.[1];
    expect(expires).toBeDefined();
    expect(new Date(expires as string).getTime()).toBeGreaterThan(Date.now());
  });

  it("declares a canonical URL", () => {
    expect(txt).toMatch(
      /^Canonical: https?:\/\/.+\/\.well-known\/security\.txt$/m,
    );
  });
});
